//
//  EnumGenerator.swift
//  VIPSGenerator
//
//  Generates Swift extensions for libvips enum and flags GTypes.
//

import VIPSIntrospection

struct EnumGenerator {

    /// Generate the Swift source for one enum or flags type.
    /// Returns `nil` if the type has no enumerable values.
    func generate(_ type: VIPSEnumType) -> String? {
        guard !type.values.isEmpty else { return nil }

        let prefix = commonPrefix(of: type.values.map { $0.name })

        var body = ""
        body += "//\n"
        body += "//  \(type.name).generated.swift\n"
        body += "//\n"
        body += "//  Generated by VIPS Swift Code Generator\n"
        body += "//  DO NOT EDIT - This file is automatically generated\n"
        body += "//\n\n"
        body += "import Cvips\n\n"
        body += "public typealias \(type.name) = Cvips.\(type.name)\n\n"
        body += "extension \(type.name) {\n"

        for value in type.values {
            let swiftName = swiftMemberName(cName: value.name, prefix: prefix)
            body += "    public static var \(swiftName): Self { \(value.name) }\n"
        }

        body += "}\n"
        return body
    }

    // MARK: - Helpers

    /// Longest common prefix of C symbol names, trimmed to end at an underscore.
    /// Example: ["VIPS_FORMAT_UCHAR", "VIPS_FORMAT_CHAR"] -> "VIPS_FORMAT_"
    private func commonPrefix(of names: [String]) -> String {
        guard let first = names.first else { return "" }
        if names.count == 1 {
            if let idx = first.lastIndex(of: "_") {
                return String(first[...idx])
            }
            return ""
        }

        var prefix = first
        for name in names.dropFirst() {
            prefix = String(zip(prefix, name).prefix(while: { $0 == $1 }).map { $0.0 })
            if prefix.isEmpty { break }
        }

        // Trim back to the last underscore so we don't slice mid-token.
        if let idx = prefix.lastIndex(of: "_") {
            return String(prefix[...idx])
        }
        return ""
    }

    /// Convert a C enum value name into a Swift member name by stripping the
    /// common prefix and camelCasing the rest.
    private func swiftMemberName(cName: String, prefix: String) -> String {
        var remainder = cName
        if remainder.hasPrefix(prefix) {
            remainder.removeFirst(prefix.count)
        }

        let lowered = remainder.lowercased()
        let tokens = lowered.split(separator: "_").map(String.init)

        // CamelCase, but keep consecutive single-character tokens lowercase so
        // `B_W` becomes `bw` (not `bW`) — matches the existing hand-written
        // convention.
        var camel = ""
        for (i, token) in tokens.enumerated() {
            guard !token.isEmpty else { continue }
            if i == 0 {
                camel += token
            } else if token.count == 1 && (tokens[i - 1].count == 1) {
                camel += token
            } else {
                camel += token.prefix(1).uppercased() + token.dropFirst()
            }
        }

        // Leading digit is not a valid Swift identifier.
        var result = camel
        if let first = result.first, first.isNumber {
            result = "_" + result
        }

        // Empty fallback (shouldn't happen, but guard).
        if result.isEmpty {
            result = "_value"
        }

        if swiftKeywords.contains(result) {
            return "`\(result)`"
        }
        return result
    }
}
